name: Bazel Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Bazelisk
      uses: bazelbuild/setup-bazelisk@v3

    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/bazel
        key: bazel-${{ runner.os }}-build

    - name: Dependency quick fix
      run: |
        wget http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb
        sudo apt install ./libtinfo5_6.2-0ubuntu2_amd64.deb

    - name: Install required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libtinfo6



    - name: Run Bazel build
      run: bazel build //hhds:all

